ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views
app_name='cart'
urlpatterns = [
    path('addtocart/<int:i>/',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cartdecrement/<int:i>/',views.cartdecrement,name="cartdecrement"),
    path('cartdelete/<int:i>/',views.cartdelete,name="cartdelete"),
    path('orderform',views.orderform,name="orderform"),
    path('paymentstatus/<str:k>/',views.paymentstatus,name="paymentstatus"),
    path('yourorders',views.yourorders,name="yourorders"),
]
from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('new/',include('search.urls')),
    path('cart/', include('cart.urls')),
]
from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path

from search import views
app_name='search'
urlpatterns = [
    path('search', views.searchnow, name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.Home.as_view(),name="category"),
    path('categorydetails/<int:pk>',views.CategoryDetails.as_view(),name="categorydetails"),
    path('productdetails/<int:pk>', views.ProductDetails.as_view(), name="productdetails"),
    path('register', views.register, name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('addcategories',views.AddCategories.as_view(),name="addcategories"),
    path('addproducts',views.AddProducts.as_view(),name="addproducts"),
    path('addstock/<int:pk>',views.AddStock.as_view(),name="addstock"),

]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    data_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price * self.quantity

class Order_Details(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address = models.TextField()
    phone = models.BigIntegerField(default=1)
    pin = models.IntegerField(default=1)
    order_id = models.CharField(max_length=30)
    payment_status = models.CharField(max_length=30, default="pending")
    delivery_status = models.CharField(max_length=30, default="pending")
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_id

    def __str__(self):
        return self.product.name



class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
import razorpay
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from cart.models import Cart,Order_Details,Payment
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from django.views.generic import View
# from cart.models import Order_Details
# Create your views here.
@login_required
def addtocart(request,i):
    u=request.user
    p=Product.objects.get(id=i)
    try:
        c=Cart.objects.get(user=u,product=p)  #retrieving user and product info from Cart table if already exists
        if(p.stock>0):
            c.quantity=c.quantity+1
            c.save()
            p.stock=p.stock-1
            p.save()
    except:
        if(p.stock>0):
            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()
            p.stock=p.stock-1
            p.save()
    return redirect('cart:cartview')

@login_required()
def cartview(request):
    u=request.user
    c=Cart.objects.filter(user=u)
    total=0
    for i in c:
        total=total+i.product.price*i.quantity
    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

def cartdecrement(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity=cart.quantity-1
            cart.save()
            p.stock=p.stock+1
            p.save()
        else:
            cart.delete()
            p.stock=p.stock+1
            p.save()
    except:
        pass
    return redirect('cart:cartview')

def cartdelete(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        cart=Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock=p.stock+cart.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')

def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        phone=request.POST['ph']
        pi=request.POST['pin']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total=int(total)
        # print(total)

        client=razorpay.Client(auth=('rzp_test_TPvy7JAPEsX7Id','0jFxJ0oiZKjxdg5zHvhkmvH6'))
        response_payment=client.order.create(dict(amount=total*100,currency='INR'))
        print(response_payment)
        order_id=response_payment['id']
        status=response_payment['status']
        if(status=='created'):
            p = Payment.objects.create(name=u.username, amount=total, order_id=order_id)
            p.save()
            for i in c:
                o = Order_Details.objects.create(product=i.product, user=i.user, phone=phone, address=a, pin=pi,
                                                order_id=order_id, no_of_items=i.quantity)
                o.save()
            context={'payment':response_payment,'name':u.username}
            return render(request,'payment.html',context)

    return render(request,'orderform.html')
@csrf_exempt
def paymentstatus(request,k):
    user=User.objects.get(username=k)
    login(request,user)
    response=request.POST
    print(response)
    param_dict={
        'razorpay_order_id':response['razorpay_order_id'],
        'razorpay_payment_id': response['razorpay_payment_id'],
        'razorpay_signature': response['razorpay_signature']
    }
    client=razorpay.Client(auth=('rzp_test_TPvy7JAPEsX7Id','0jFxJ0oiZKjxdg5zHvhkmvH6'))
    try:
        status=client.utility.verify_payment_signature(param_dict)
        print(status)
        m=Payment.objects.get(order_id=response['razorpay_order_id'])
        m.paid=True
        m.razorpay_payment_id=response['razorpay_payment_id']
        m.save()
        o=Order_Details.objects.filter(order_id=response['razorpay_order_id'])
        for i in o:
            i.payment_status="Completed"
            i.save()
        c=Cart.objects.filter(user=user)
        c.delete()


    except:
        pass

    return render(request,'paymentstatus.html')

def yourorders(request):
    u=request.user
    o=Order_Details.objects.filter(user=u,payment_status="Completed")
    context={'orders':o}
    return render(request,'yourorders.html',context)

ecommerce/search/views.py
from django.db.models import Q
from django.shortcuts import render
from shop.models import Product
# Create your views here.

def searchnow(request):
    p=None
    query=""
    if request.method== "POST":
        query=request.POST['q']
        if query:
            p=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'key':p})

ecommerce/templates/addcategories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}

<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>

{% endblock %}
{% block content %}
<div class="container mt-5 border border-dark mb-5">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<table>
  {{form.as_table}}
</table>
<button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>
{% endblock %}

ecommerce/templates/addproducts.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}


<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>

{% endblock %}
{% block content %}
<div class="container mt-5 border border-dark mb-5">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<table>
  {{form.as_table}}
</table>
<button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}


<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>

{% endblock %}
{% block content %}
<div class="container mt-5 border border-dark mb-5">
    <h1>Update Stock</h1>
<form method="POST">
  {% csrf_token %}
<table>
  {{form.as_table}}
</table>
<button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>
{% endblock %}

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}

<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>
{% endblock %}


{% block content %}
<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">

				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-image">Product Image</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>
									<th>Subtotal</th>
									<th>Operations</th>
								</tr>
							</thead>
							<tbody>
							{% for i in cart %}
								<tr class="table-body-row">
									<td class="product-image"><img src="{{i.product.image.url}}" alt=""></td>
									<td class="product-name">{{i.product.name}}</td>
									<td class="product-price">{{i.product.price}}</td>
									<td class="product-quantity">{{i.quantity}}</td>
									<td>{{i.subtotal}}</td>
									<td>
									{% if i.product.stock > 0 %}
									<a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-regular fa-square-plus m-2"></i></a><a href="{% url 'cart:cartdecrement' i.product.id %}"><i class="fa-regular fa-square-minus "></i></a><a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-regular fa-trash-can m-2"></i></a>
									{% else %}
									<a href="{% url 'cart:cartdecrement' i.product.id %}"><i class="fa-regular fa-square-minus m-2"></i></a><a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-regular fa-trash-can m-2"></i></a>
									{% endif %}
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>Total</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody>
								<tr class="total-data">
									<td><strong>Total: </strong></td>
									<td>{{total}}</td>
								</tr>
							</tbody>
						</table>
						<div class="cart-buttons">
							<a href="{% url 'cart:orderform' %}" class="boxed-btn">Place Order</a>
							<a href="checkout.html" class="boxed-btn black">Continue Shopping</a>
						</div>
					</div>

					<div class="coupon-section">
						<h3>Apply Coupon</h3>
						<div class="coupon-form-wrap">
							<form action="index.html">
								<p><input type="text" placeholder="Coupon"></p>
								<p><input type="submit" value="Apply"></p>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<h2 class="text-center mt-3">Our Collections</h2>
<p>Welcome to [Your Store Name], your one-stop destination for quality, convenience, and style! We offer a vast range of products, from the latest fashion trends and cutting-edge tech to home essentials and unique gifts. Our easy-to-navigate online store ensures a smooth shopping experience, with secure payment options and fast, reliable shipping. Whether you're searching for something special or just browsing, we make online shopping a breeze with top-notch customer service and unbeatable prices. Explore, shop, and discover something you'll love today!</p>

<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">
						<h3><span class="orange-text">Our</span> Products</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>

            <div class="row">
                {% for i in key %}
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="{{i.image.url}}" height="200px" alt=""></a>
						</div>
						<h3>{{i.name}}</h3>
						<a href="{% url 'shop:categorydetails' i.id %}" class="cart-btn">Shop Now</a>
					</div>
				</div>
                 {% endfor %}
            </div>


        </div>

    </div>
{% endblock %}

ecommerce/templates/categorydetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block bg %}
<div class="hero-area" style="background-image: url('{{k.image.url}}');">
		<div class="container">
			<div class="row">
				<div class="col-lg-9 offset-lg-2 text-center">
					<div class="hero-text">
						<div class="hero-text-tablecell">
							<h1>{{k.name}}</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block content %}

<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">
						<h3><span class="orange-text">Our</span> Products</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>

            <div class="row">
                {% for i in k.products.all %}
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="{{i.image.url}}" height="200px" alt=""></a>
						</div>
						<h3>{{i.name}}</h3>
                        <h3>{{i.price}}</h3>
                        <a href="{% url 'shop:productdetails' i.id %}" class="cart-btn">Details</a>

					</div>
				</div>
                 {% endfor %}
            </div>


        </div>

    </div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 border border-dark">
<form method="POST">
    {% csrf_token %}
    <div class="container border border-3px mt-5 mb-5">
<div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  </div>
<div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
<div class="mb-3">
    <input type="submit" class="btn btn-info">
</div>
    </div>
    </form>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

ecommerce/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hello
</body>
</html>

ecommerce/templates/orderform.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}


<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>

{% endblock %}
{% block content %}
<div class="container mt-5 border border-dark">
<form method="POST">
    {% csrf_token %}
    <div class="container border border-3px mt-5 mb-5">
        <h2>Billing Details.</h2>
<div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a">
  </div>
<div class="mb-3">
    <label class="form-label">Pin</label>
    <input type="number" class="form-control" name="pin">
  </div>
        <div class="mb-3">
    <label class="form-label">Phone</label>
    <input type="number" class="form-control" name="ph">
  </div>
<div class="mb-3">
    <input type="submit" class="btn btn-info">
</div>
    </div>
    </form>
</div>
{% endblock %}

ecommerce/templates/paymentstatus.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}


<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
{% endblock %}
{% block content %}
<div class="bg-dark" style="height:80px;"></div>
<h2>Payment Successful.</h2>
{% endblock %}

ecommerce/templates/productdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block bg %}

<!--	<div class="hero-area" style="background-image: url('{% static 'img/dark.jpg' %}');">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<div class="col-lg-9 offset-lg-2 text-center">-->
<!--					<div class="hero-text">-->
<!--						<div class="hero-text-tablecell">-->
<!--							<p class="subtitle">Welcome to {{n.name}}</p>-->
<!--							<h1>Product Details</h1>-->
<!--							<div class="hero-btns">-->
<!--								<a href="shop.html" class="boxed-btn">Fruit Collection</a>-->
<!--								<a href="contact.html" class="bordered-btn">Contact Us</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	&lt;!&ndash; end hero area &ndash;&gt;-->
<div class="h-25 bg-dark"></div>

{% endblock %}
{% block content %}
<!-- single product -->
	<div class="single-product mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<div class="single-product-img">
						<img src="{{n.image.url}}" alt="">
					</div>
				</div>
				<div class="col-md-7">
					<div class="single-product-content">
						<h3>{{n.name}}</h3>
						<p class="single-product-pricing">₹{{n.price}}</p>
                        <p>Available Stock:{{n.stock}}</p>
                        <p>{{n.description}}</p>
						<div class="single-product-form">
							<form action="index.html">
								<input type="number" placeholder="0">
							</form>
							{% if user.is_superuser %}
								{% if n.stock > 0 %}
									<p class="text-success">Product In Stock</p>
									<a href="{% url 'shop:addstock' n.id %}" class="btn btn-primary">Add Stock</a>
								{% else %}
									<p class="text-danger">Product Out of Stock</p>
									<a href="{% url 'shop:addstock' n.id %}" class="btn btn-primary">Add Stock</a>
								{% endif %}
							{% else %}
								{% if n.stock > 0 %}
									<a href="{% url 'cart:addtocart' n.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
								{% else %}
									<p class="text-danger">Product Out of Stock</p>
								{% endif %}
							{% endif %}


							<p><strong>Categories: </strong>Fruits, Organic</p>
						</div>
						<h4>Share:</h4>
						<ul class="product-share">
							<li><a href=""><i class="fab fa-facebook-f"></i></a></li>
							<li><a href=""><i class="fab fa-twitter"></i></a></li>
							<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
							<li><a href=""><i class="fab fa-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end single product -->

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 border border-dark">
<form method="POST">
    {% csrf_token %}
    <div class="container border border-3px mt-5 mb-5">
  <div class="mb-3">
    <label class="form-label">Email address</label>
    <input type="email" class="form-control" name="e">
  </div>
   <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
    <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  </div>
     <div class="mb-3">
    <label class="form-label">First Name</label>
    <input type="text" class="form-control" name="f">
  </div>
     <div class="mb-3">
    <label class="form-label">Last Name</label>
    <input type="text" class="form-control" name="l">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>
</div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% if key %}
 <div class="row">
                {% for i in key %}
				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							<a href="single-product.html"><img src="{{i.image.url}}" height="200px" alt=""></a>
						</div>
						<h3>{{i.name}}</h3>
                        <h3>{{i.price}}</h3>
                        <a href="{% url 'shop:productdetails' i.id %}" class="cart-btn">Details</a>

					</div>
				</div>
                 {% endfor %}
            </div>
{% else %}
	<h2>No Results Found!!!!</h2>
{% endif %}
{% endblock %}

ecommerce/templates/yourorders.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<h3 class="text-center">Here are your Orders,{{user.username}}</h3>
<table class="table table-bordered table-secondary w-75 mx-auto">
    <tr>
        <th>Product Image</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Number of items</th>
        <th>Order ID</th>
        <th>Order On</th>
        <th>Delivery Status</th>
    </tr>
    {% for i in orders %}
    <tr>
        <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
        <td>{{i.product.name}}</td>
        <td>{{i.product.price}}</td>
        <td>{{i.no_of_items}}</td>
        <td>{{i.order_id}}</td>
        <td>{{i.ordered_date}}</td>
        <td>{{i.delivery_status}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}